Share envs between the triggered workflows and the parent build (#6)
* feat: add an option to share the provided envs with the triggered workflows

- step.yml: add the environment_key_list input. With that you can specify which envs do you want to share with the triggered worklflows.
- bitrise/bitrise.go: add the Environment struct.
- test added to test the environment_key_list input parsing

* test: test fix

* sourceBuildNumber param converted to the new Environment struct

* test: add test_shared_envs workfows to the bitrise.yml

* fix: chage the break command to continue in the loop which creates the shared envs for the request

* docs: remove the note from the `environment_key_list` input in the step.yml

* fix: typo fix

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -12,6 +12,11 @@ app:
 
 workflows:
   test:
+    envs:
+    - ENV_1: "1"
+    - ENV_2: "2"
+    - ENV_3: "3"
+    - ENV_4: "4"
     before_run:
     - audit-this-step
     steps:
@@ -24,6 +29,23 @@ workflows:
         - workflows: $TEST_WORKFLOWS
         - access_token: $ACCESS_TOKEN
         - wait_for_builds: "true"
+        - environment_key_list: "ENV_1\nENV_2\n$ENV_3\n$ENV_4\n"
+
+  test_shared_envs:
+    steps:
+    - script@1.1.5:
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -e
+            
+            echo "ENV_1 = $ENV_1 ENV_2 = $ENV_2 ENV_3 = $ENV_3 ENV_4 = $ENV_4"
+            if [[ "$ENV_1" != "1" ]] || [[ "$ENV_2" != "2" ]] || [[ "$ENV_3" != "3" ]] || [[ "$ENV_4" != "4" ]] ; then
+              exit 1;
+            else
+              echo "got all of the exported environments"
+            fi
 
   # ----------------------------------------------------------------
   # --- workflows to Share this step into a Step Library
